services:
  # Backend Principal Unificado (para ambos sistemas)
  - type: web
    name: backend-unificado
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: CORS_ORIGIN
        value: https://alcaldia-frontend.onrender.com
    healthCheckPath: /health
    healthCheckTimeout: 180
    autoDeploy: true

  # Frontend de la Alcaldía
  - type: web
    name: alcaldia-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l 3000
    envVars:
      - key: PORT
        value: 3000
